# Generated by Django 4.1.1 on 2022-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_apartment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('LAPTOPS', 'Laptops'), ('COMPONENTS', 'Components'), ('MICE', 'Mice'), ('KEYBOARDS', 'Keyboards'), ('AUDIO', 'Audio'), ('STREAMING', 'Streaming'), ('CHAIRS', 'Chairs'), ('CONSOLE', 'Console')], max_length=10),
        ),
    ]
